---
- name: Copy nginx server block configs
  template:
    src: "{{ nginx_conf_src }}"
    dest: "{{ nginx_conf_dst }}"
    backup: false
  notify:
    - Reload nginx

- name: Create ssl dir
  file:
    path: "{{ nginx_cert_dir }}"
    state: directory
    mode: 0755

- name: Copy servers cert
  template:
    src: "{{ nginx_cert_src }}"
    dest: "{{ nginx_cert_dst }}"
    owner: root
    group: root
    mode: 0644
    backup: false
  notify:
    - Reload nginx

- name: Copy servers key
  template:
    src: "{{ nginx_key_src }}"
    dest: "{{ nginx_key_dst }}"
    owner: root
    group: root
    mode: 0400
    backup: false
  notify:
    - Reload nginx
