---
- name: Update uhttpd config
  template:
    src: "{{ uhttpd_conf_src }}"
    dest: "{{ uhttpd_conf_dst }}"
    backup: false
  notify:
    - Reload uhttpd
  when: ansible_distribution == 'OpenWrt'

- name: Update nginx server config
  template:
    src: "{{ nginx_conf_src }}"
    dest: "{{ nginx_conf_dst }}"
    backup: false
  notify:
    - Reload nginx

- name: Create ssl dir
  file:
    path: "{{ nginx_cert_dir }}"
    state: directory
    mode: 0755

- name: Update servers cert
  template:
    src: "{{ nginx_cert_src }}"
    dest: "{{ nginx_cert_dst }}"
    owner: root
    group: root
    mode: 0644
    backup: false
  notify:
    - Reload nginx

- name: Update servers key
  template:
    src: "{{ nginx_key_src }}"
    dest: "{{ nginx_key_dst }}"
    owner: root
    group: root
    mode: 0400
    backup: false
  notify:
    - Reload nginx

- name: Assign main nginx config for OpenWRT
  shell: 'nginx -T -c /etc/nginx/uci.conf'
  when: ansible_distribution == 'OpenWrt'
