---
- name: Create scripts directory
  file:
    path: "{{ openconnect_scripts_dst }}"
    state: directory

- name: Update openconnect scripts
  template:
    src:  "{{ item }}"
    dest: "{{ openconnect_scripts_dst }}/{{ item | basename | regex_replace('_script','') | regex_replace('.j2','') }}"
    mode: 0755
  with_fileglob:
     - "{{ openconnect_scripts_tmpl }}"
  tags:
  - update_openconnect_scripts

- name: Update procd scripts
  template:
    src:  "{{ item }}"
    dest: "{{ openconnect_procd_dst }}/{{ item | basename | regex_replace('_procd','') | regex_replace('.j2','') }}"
    mode: 0755
  with_fileglob:
     - "{{ openconnect_procd_tmpl }}"
  tags:
  - update_procd_scripts

- name: Start and enable openconnect services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ openconnect_services }}"

- name: Update network settings
  template:
    src: "{{ network_src }}"
    dest: "{{ network_dst }}"
    mode: 0600
  notify:
    - Restart network
  tags:
  - update_network_settings

- name: Update firewall settings
  template:
    src: "{{ firewall_src }}"
    dest: "{{ firewall_dst }}"
  notify:
    - Reload firewall
  tags:
  - update_firewall_settings

- name: Trigger final stop/start openconnect services
  command: /bin/true
  notify: 
    - Stop/start openconnect
  tags:
  - always
