---
- hosts: all
  become: true
  roles:
    - pkg-install
  vars:
    apt_package_names:
      - vim
      - gnupg
      - curl
      - sudo
      - traceroute

- import_playbook: add-user.yml
- import_playbook: add-ca-certificates.yml
- import_playbook: upgrade-packages.yml
