---
uhttpd_conf_src: files/router/config/uhttpd
uhttpd_conf_dst: /etc/config/uhttpd
nginx_conf_src: universal.conf.j2
nginx_conf_dst: /etc/nginx/conf.d/{{ inventory_hostname }}.conf
nginx_cert_dir: /etc/pki/nginx
nginx_cert_src: files/certificates/sapkyy_home.crt
nginx_cert_dst: "{{ nginx_cert_dir }}/sapkyy.home.crt"
nginx_key_src: sapkyy.home.key.j2
nginx_key_dst: "{{ nginx_cert_dir }}/sapkyy.home.key"
