---
- name: Restart network
  service:
    name: network
    state: restarted

- name: Reload firewall
  service:
    name: firewall
    state: reloaded

- name: Stop openconnect services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: true
  with_items: "{{ openconnect_services }}"
  listen: "Stop/start openconnect"

- name: Start openconnect services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ openconnect_services }}"
  listen: "Stop/start openconnect"
