---
- name: Restart network
  service:
    name: network
    state: restarted

- name: Reload firewall
  service:
    name: firewall
    state: reloaded

- name: Restart pbr
  service:
    name: pbr
    state: restarted

- name: Stop openvpn services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: true
  with_items: "{{ openvpn_services }}"
  listen: "Stop/start openvpn"

- name: Start openvpn services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ openvpn_services }}"
  listen: "Stop/start openvpn"
