---
ovpn_files_src: files/openvpn/
ovpn_files_dst: /etc/openvpn/client
ovpn_scripts_src: openvpn.service
ovpn_scripts_dst: /etc/openvpn/scripts
ovpn_scripts_tmpl: templates/openvpn_tun*script.sh.j2
ovpn_procd_dst: /etc/init.d
ovpn_procd_tmpl: templates/openvpn_tun*procd.j2
network_src: files/router/config/network.j2
network_dst: /etc/config/network
firewall_src: files/router/config/firewall
firewall_dst: /etc/config/firewall
pbr_src: files/router/config/pbr.j2
pbr_dst: /etc/config/pbr 
ovpn_services:
  - openvpn_tun10
  - openvpn_tun11
