---
- name: Restart network
  service:
    name: network
    state: restarted

- name: Reload firewall
  service:
    name: firewall
    state: reloaded

- name: Restart pbr
  service:
    name: pbr
    state: restarted
    
- name: Restart rpcd
  service:
    name: rpcd
    state: restarted

- name: Restart openvpn services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items: "{{ ovpn_services }}"
