---
# tasks file for add_keys
- name: Creates .ssh directory
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Add authorized keys for root user
  template:
    src: "files/add_keys/authorized_keys"
    dest: "/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: 0700

