---
- name: Update sapkyy.home zone
  template:
    src: "{{ sapkyy_zone_src }}"
    dest: "{{ sapkyy_zone_dst }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload bind

- name: Update work config
  template:
    src: "{{ work_conf_src }}"
    dest: "{{ work_conf_dst }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload bind
