---
- name: Update openvpn files
  copy:
    src: "{{ item }}"
    dest: "{{ ovpn_files_dst }}"
  with_fileglob:
    - "{{ ovpn_files_src }}*"
  tags:
  - update_openvpn_files

- name: Create scripts directory
  file:
    path: "{{ ovpn_scripts_dst }}"
    state: directory

- name: Update openvpn scripts
  template:
    src:  "{{ item }}"
    dest: "{{ ovpn_scripts_dst }}/{{ item | basename | regex_replace('_script','') | regex_replace('.j2','') }}"
    mode: 0755
  with_fileglob:
     - "{{ ovpn_scripts_tmpl }}"
  tags:
  - update_openvpn_scripts

- name: Update procd scripts
  template:
    src:  "{{ item }}"
    dest: "{{ ovpn_procd_dst }}/{{ item | basename | regex_replace('_procd','') | regex_replace('.j2','') }}"
    mode: 0755
  with_fileglob:
     - "{{ ovpn_procd_tmpl }}"
  tags:
  - update_procd_scripts

- name: Start and enable openvpn services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ ovpn_services }}"

- name: Update network settings
  template:
    src: "{{ network_src }}"
    dest: "{{ network_dst }}"
    mode: 0600
  notify:
    - Restart network
  tags:
  - update_network_settings

- name: Update firewall settings
  template:
    src: "{{ firewall_src }}"
    dest: "{{ firewall_dst }}"
  notify:
    - Reload firewall
  tags:
  - update_firewall_settings

- name: Update pbr settings
  template:
    src: "{{ pbr_src }}"
    dest: "{{ pbr_dst }}"
  notify:
    - Restart pbr
  tags:
  - update_pbr_settings

- name: Trigger final stop/start openvpn openvpn services
  command: /bin/true
  notify: 
    - Stop/start openvpn
  tags:
  - always
