---
- name: Add openvpn files
  copy:
    src: "{{ item }}"
    dest: "{{ ovpn_files_dst }}"
  with_fileglob:
    - "{{ ovpn_files_src }}*"

- name: Create scripts directory
  file:
    path: "{{ ovpn_scripts_dst }}"
    state: directory

- name: Copy openvpn scripts
  template:
    src:  "{{ item }}"
    dest: "{{ ovpn_scripts_dst }}/{{ item | basename | regex_replace('_script','') | regex_replace('.j2','') }}"
    mode: 0755
  with_fileglob:
     - "{{ ovpn_scripts_tmpl }}"

- name: Copy procd scripts
  template:
    src:  "{{ item }}"
    dest: "{{ ovpn_procd_dst }}/{{ item | basename | regex_replace('_procd','') | regex_replace('.j2','') }}"
    mode: 0755
  with_fileglob:
     - "{{ ovpn_procd_tmpl }}"

- name: Start and enable openvpn services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ ovpn_services }}"

- name: Sync network settings
  template:
    src: "{{ network_src }}"
    dest: "{{ network_dst }}"
    mode: 0600
  notify:
    - Restart network

- name: Allow wan access for tun interfaces
  template:
    src: "{{ firewall_src }}"
    dest: "{{ firewall_dst }}"
  notify:
    - Reload firewall

- name: Add route tables
  template:
    src: "{{ route_tables_src }}"
    dest: "{{ route_tables_dst }}"

- name: Add table routing
  template:
    src: "{{ table_route_src }}"
    dest: "{{ table_route_dst }}"
  notify:
    - Restart network

- name: Final restart openvpn services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items: "{{ ovpn_services }}"
